version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vavjs3
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: 'production'
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vavjs_zadanie3
